vich_uploader:
  db_driver: orm
  metadata:
   type: attribute

  mappings:
    recipe_images:
      uri_prefix: /recipe_images'
      upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 